services:
  proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.postgres.address=:5432"
      - "--entrypoints.web.address=:3000"
      - "--entrypoints.api.address=:5002"
    ports:
      - "6969:8080" # Traefik dashboard
      - "5432:5432" # PostgreSQL port
      - "5002"
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  evanbecker-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${Prod_DB_USER}
      - POSTGRES_PASSWORD=${Prod_DB_PASSWORD}
    volumes:
      - ./appdata/postgres:/var/lib/postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entryPoints=postgres"
      - "traefik.tcp.routers.postgres.service=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

  evanbecker:
    container_name: evanbecker-server
    build:
      context: .
      dockerfile: evanbecker-api/Dockerfile
    image: ${DOCKER_REGISTRY-}evanbecker
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"
    depends_on:
      - evanbecker-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aspnetapp.rule=Host(`api.localhost`)"
      - "traefik.http.routers.aspnetapp.entrypoints=api"

  evanbecker-client:
    container_name: evanbecker-client
    build:
      context: evanbecker-client
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}evanbecker-client
    depends_on:
      - evanbecker-db
      - evanbecker
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.routers.client.rule=Host(`localhost`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
