services:
  proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # TODO: Test if 5430 is valid for postgresql
      - "--entrypoints.postgres.address=:5430"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.api.address=:5002"
      - "--entrypoints.apisecure.address=:5003"
      - "--api.dashboard=true"
    ports:
      - "6969:8080" # Traefik dashboard
      - "5432:5432" # PostgreSQL port
      - "5002"
      - "5003"
      - "80"
      - "443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik-test.evanbecker.net`)"
      - "traefik.http.routers.api.service=api@internal"

  evanbecker-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./appdata/postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`db-test.evanbecker.net`)"
      - "traefik.tcp.routers.postgres.entryPoints=postgres"
      - "traefik.tcp.routers.postgres.service=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

  evanbecker:
    container_name: evanbecker-server
    pull_policy: always
    image: registry.digitalocean.com/evanbecker/evanbecker-server
    environment:
      - Auth0__Domain=${Auth0_Domain}
      - Auth0__Audience=${Auth0_Audience}
      - Auth0__ClientId=${Auth0_ClientId}
      - Auth0__ClientSecret=${Auth0_ClientSecret}
      - Auth0__Url=${Auth0_Url}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      # TODO: Grab cert from server paths
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/evanbecker.net.pfx

    ports:
      - "5002:80"
      - "5003:443"
    depends_on:
      - evanbecker-db
    volumes:
      - ~/.aspnet/https:/https:ro
      - /certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aspnetapp.rule=Host(`api-test.evanbecker.net`)"
      - "traefik.http.routers.aspnetapp.entrypoints=api"    
      - "traefik.http.routers.aspnetapp.entrypoints=apisecure"   
      
  evanbecker-client:
    container_name: evanbecker-client
    pull_policy: always
    image: registry.digitalocean.com/evanbecker/evanbecker-client
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI}
    depends_on:
      - evanbecker-db
      - evanbecker
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - /certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.entrypoints=web,websecure"
      - "traefik.http.routers.client.rule=Host(`test.evanbecker.net`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000" # I'm setting up the reverse proxy to target 3000 as we defined in the Dockerfile.
      - "traefik.port=80"