name: Build & Deploy Test

on:
  push:
    branches: [ "develop" ]

env:
  REGISTRY: 192.168.0.168:5000

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create client .env.local
        run: |
          cat > ./evanbecker-client/.env.local << 'EOF'
          NEXT_PUBLIC_SITE_URL=https://test.evanbecker.net
          NEXT_PUBLIC_API_URL=https://api-test.evanbecker.net
          NEXT_PUBLIC_AUTH0_DOMAIN=dev-m3uiopcp.us.auth0.com
          NEXT_PUBLIC_AUTH0_CLIENT_ID=2evqEjBNUmBVt6fNwcGkicfjNNrYsjV0
          NEXT_PUBLIC_AUTH0_AUDIENCE=evanbecker.api
          NEXT_PUBLIC_AUTH0_REDIRECT_URI=https://test.evanbecker.net
          EOF

      - name: Build images
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/evanbecker-api:test \
            -t ${{ env.REGISTRY }}/evanbecker-api:test-${{ github.sha }} \
            -f evanbecker-api/Dockerfile .
          docker build \
            -t ${{ env.REGISTRY }}/evanbecker-client:test \
            -t ${{ env.REGISTRY }}/evanbecker-client:test-${{ github.sha }} \
            -f evanbecker-client/Dockerfile .

      - name: Push to local registry
        run: |
          docker push ${{ env.REGISTRY }}/evanbecker-api:test
          docker push ${{ env.REGISTRY }}/evanbecker-api:test-${{ github.sha }}
          docker push ${{ env.REGISTRY }}/evanbecker-client:test
          docker push ${{ env.REGISTRY }}/evanbecker-client:test-${{ github.sha }}

      - name: Clean up old images
        run: docker image prune -f
