name: Build & Deploy Prod

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: 192.168.0.168:5000

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/evanbecker-api:latest \
            -t ${{ env.REGISTRY }}/evanbecker-api:${{ github.sha }} \
            -f evanbecker-api/Dockerfile .
          docker build \
            --build-arg NUXT_PUBLIC_SITE_URL=https://www.evanbecker.net \
            --build-arg NUXT_PUBLIC_API_URL=https://api.evanbecker.net \
            --build-arg NUXT_PUBLIC_AUTH0_DOMAIN=evanbecker.us.auth0.com \
            --build-arg NUXT_PUBLIC_AUTH0_CLIENT_ID=JOV7J3Qv3XzFD3xyQjDEW03PtaU8bpqc \
            --build-arg NUXT_PUBLIC_AUTH0_AUDIENCE=api.evanbecker.net \
            --build-arg NUXT_PUBLIC_AUTH0_REDIRECT_URI=https://www.evanbecker.net \
            -t ${{ env.REGISTRY }}/evanbecker-client:latest \
            -t ${{ env.REGISTRY }}/evanbecker-client:${{ github.sha }} \
            evanbecker-client

      - name: Push to local registry
        run: |
          docker push ${{ env.REGISTRY }}/evanbecker-api:latest
          docker push ${{ env.REGISTRY }}/evanbecker-api:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/evanbecker-client:latest
          docker push ${{ env.REGISTRY }}/evanbecker-client:${{ github.sha }}

      - name: Clean up old images
        run: docker image prune -f
