name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request: #TODO: Comment this part out
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        
      - name: Create env files
        run: |
          touch .env
          echo -e "${{ secrets.SERVER_ENV_PROD }}\n" > .env

          echo "Client Secrets"
          echo -e "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}\n" >> .env
          echo -e "NEXT_PUBLIC_AUTH0_DOMAIN=${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}\n" >> .env
          echo -e "NEXT_PUBLIC_AUTH0_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}\n" >> .env
          echo -e "NEXT_PUBLIC_AUTH0_AUDIENCE=${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}\n" >> .env
          echo -e "NEXT_PUBLIC_AUTH0_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_AUTH0_REDIRECT_URI }}\n" >> .env

          echo "API Secrets"
          echo -e "Auth0_Domain=${{ secrets.Auth0_Domain }}\n" >> .env
          echo -e "Auth0_Audience=${{ secrets.Auth0_Audience }}\n" >> .env
          echo -e "Auth0_ClientId=${{ secrets.Auth0_ClientId }}\n" >> .env
          echo -e "Auth0_ClientSecret=${{ secrets.Auth0_ClientSecret }}\n" >> .env
          echo -e "Auth0_Url=${{ secrets.Auth0_Url }}\n" >> .env
          echo -e "ReCaptcha_Secret=${{ secrets.ReCaptcha_Secret }}\n" >> .env

          echo "Docker Secrets"
          echo -e "DB_NAME=${{ secrets.DB_NAME }}\n" >> .env
          echo -e "DB_USER=${{ secrets.DB_USER }}\n" >> .env
          echo -e "DB_PASS=${{ secrets.DB_PASS }}\n" >> .env
          echo -e "ENVIRONMENT=${{ secrets.ENVIRONMENT }}\n" >> .env
          
          cat .env

      - name: Build image
        run: docker compose -f docker-compose.test.yaml build
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
        
      - name: Push image to DO Container Registry
        run: docker compose -f docker-compose.test.yaml push
        
      - name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GL_SSH_HOST }}
          username: ${{ secrets.GL_SSH_USERNAME }}
          key: ${{ secrets.GL_SSH_SECRET }}
          port: ${{ secrets.GL_SSH_PORT }}
          script: |
            cd /PATH/TO/DIRECTORY/WHERE/COMPOSE/FILE/IS
            ./init.sh
